### ISSUE TITLE
LDAP_PORT not set correctly

### ISSUE THREAD

**Issue by dcendents** [tiredofit/docker-fusiondirectory#10]
As I mentioned in my comment to #9, the LDAP port when using LDAP_TLS=TRUE is not set in the file fusiondirectory.conf.

I tracked down the problem to the init script:

```bash
        LDAP_PORT=LDAP${i}_PORT

        if [ "${!LDAP_TLS}" = "TRUE" ] ; then
            LDAP_SCHEME="ldaps"
            LDAP_PORT=636
        fi

        if [ "${!LDAP_PORT}" = "" ] ; then
            LDAP_PORT=389
        fi
```

Then later on: `<referral URI='${LDAP_SCHEME}://${!LDAP_HOST}:${!LDAP_PORT}...`

Variable indirection is used: `${!LDAP_PORT}`, which is fine when its value is `LDAP${i}_PORT`, but will not work when the value is explicitely set to 389 or 636.

**Comment by dcendents** [comment]
As a temporary fix, the following Dockerfile will fix it:

```bash
FROM tiredofit/fusiondirectory:1.16

RUN sed -i '417d' /etc/cont-init.d/10-fusiondirectory
```

Make sure to declare the value for `LDAP1_PORT=636`.

**Comment by tiredofit** [comment]
To look into and solve in short order! I will review and see where I've gone wrong here.

**Comment by tiredofit** [comment]
Thanks again for the find. I've pushed a new tag `1.17` and `latest` that resolves this issue.

**Comment by dcendents** [comment]
Hi @tiredofit , I'm sorry to say but version `1.17` does not solve the problem.

I do not see any modifications in the script https://github.com/tiredofit/docker-fusiondirectory/blob/master/install/etc/cont-init.d/10-fusiondirectory. On my side I have the same result, the port number is missing in the file `/etc/fusiondirectory/fusiondirectory.conf`

**Comment by tiredofit** [comment]
I've recomitted a new release 1.17.1 - Docker Hub is going berzerk on me right now so might be a day to get a new image built.

**Comment by tiredofit** [comment]
@dcendents I've just manually pushed one to skip past docker hubs auto builds - `tiredofit/fusiondirectory:1.17.1`

**Comment by dcendents** [comment]
Thanks @tiredofit it is working now with `tiredofit/fusiondirectory:1.17.1`
